"""Demo data generator — ~30 realistic German business invoices for Q1 2024."""

from db import insert_invoice, clear_all_invoices, get_invoices

# ---------------------------------------------------------------------------
# Realistic demo invoices (Q1 2024, German freelance/small business context)
# ---------------------------------------------------------------------------
DEMO_INVOICES = [
    # ---- AUTO-TRIAGED: OK (VST_19 - German domestic 19%) ----
    {
        "filename": "hetzner_2024-01.pdf",
        "vendor": "Hetzner Online GmbH",
        "invoice_date": "2024-01-01",
        "invoice_number": "R2401-2847391",
        "amount_net": 14.24,
        "amount_vat": 2.71,
        "amount_gross": 16.95,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.97,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Hetzner Online GmbH · Rechnung · Netto: 14,24 EUR · MwSt. 19%: 2,71 EUR · Brutto: 16,95 EUR",
    },
    {
        "filename": "ionos_jan2024.pdf",
        "vendor": "IONOS SE",
        "invoice_date": "2024-01-03",
        "invoice_number": "INV-DE-2024-00183742",
        "amount_net": 9.99,
        "amount_vat": 1.90,
        "amount_gross": 11.89,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.96,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "IONOS SE · Rechnung Nr. INV-DE-2024-00183742 · Nettobetrag: 9,99 EUR · USt 19%: 1,90 EUR",
    },
    {
        "filename": "telekom_jan2024.pdf",
        "vendor": "Deutsche Telekom AG",
        "invoice_date": "2024-01-05",
        "invoice_number": "TK-2024-01-9847622",
        "amount_net": 39.50,
        "amount_vat": 7.51,
        "amount_gross": 47.01,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.98,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Deutsche Telekom AG · Rechnung Mobilfunk · Rechnungsbetrag netto: 39,50 EUR · Umsatzsteuer 19%: 7,51 EUR",
    },
    {
        "filename": "datev_q1_2024.pdf",
        "vendor": "DATEV eG",
        "invoice_date": "2024-01-08",
        "invoice_number": "DATEV-2024-01-003841",
        "amount_net": 54.20,
        "amount_vat": 10.30,
        "amount_gross": 64.50,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.96,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "DATEV eG · Rechnung für Steuerberatungssoftware · Netto: 54,20 EUR · MwSt 19%: 10,30 EUR",
    },
    {
        "filename": "microsoft365_jan.pdf",
        "vendor": "Microsoft Ireland Operations Ltd.",
        "invoice_date": "2024-01-10",
        "invoice_number": "G010282847-DE",
        "amount_net": 10.90,
        "amount_vat": 2.07,
        "amount_gross": 12.97,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "IE",
        "status": "ok",
        "confidence": 0.88,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Microsoft Ireland Operations Ltd · Microsoft 365 Business Basic · DE VAT charged at 19%: 2,07 EUR",
    },
    {
        "filename": "sevdesk_jan2024.pdf",
        "vendor": "sevDesk GmbH",
        "invoice_date": "2024-01-12",
        "invoice_number": "SD-2024-00892",
        "amount_net": 13.90,
        "amount_vat": 2.64,
        "amount_gross": 16.54,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.95,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "sevDesk GmbH · Buchhaltungssoftware · Netto: 13,90 EUR · USt 19%: 2,64 EUR",
    },
    {
        "filename": "adobe_jan2024.pdf",
        "vendor": "Adobe Systems Software Ireland Ltd.",
        "invoice_date": "2024-01-15",
        "invoice_number": "IE-2024-ADOBECC-83726",
        "amount_net": 54.95,
        "amount_vat": 10.44,
        "amount_gross": 65.39,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "IE",
        "status": "ok",
        "confidence": 0.87,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Adobe Systems Software Ireland Ltd. · Creative Cloud All Apps · German VAT 19%: 10,44 EUR",
    },
    {
        "filename": "hetzner_2024-02.pdf",
        "vendor": "Hetzner Online GmbH",
        "invoice_date": "2024-02-01",
        "invoice_number": "R2402-2951827",
        "amount_net": 42.86,
        "amount_vat": 8.14,
        "amount_gross": 51.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.97,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Hetzner Online GmbH · Dedicated Server + Cloud · Netto: 42,86 EUR · MwSt. 19%: 8,14 EUR",
    },
    {
        "filename": "netcup_feb2024.pdf",
        "vendor": "netcup GmbH",
        "invoice_date": "2024-02-03",
        "invoice_number": "NC-2024-028371",
        "amount_net": 6.72,
        "amount_vat": 1.28,
        "amount_gross": 8.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.94,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "netcup GmbH · VPS Server · Netto: 6,72 EUR · USt 19%: 1,28 EUR",
    },
    {
        "filename": "buero_bedarf_feb.pdf",
        "vendor": "Viking Direct GmbH",
        "invoice_date": "2024-02-14",
        "invoice_number": "DE-VD-2024-374821",
        "amount_net": 73.95,
        "amount_vat": 14.05,
        "amount_gross": 88.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.85,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Viking Direct GmbH · Bürobedarf: Druckerpatronen, Papier · Netto: 73,95 EUR · MwSt 19%: 14,05 EUR",
    },
    {
        "filename": "telekom_mar2024.pdf",
        "vendor": "Deutsche Telekom AG",
        "invoice_date": "2024-03-05",
        "invoice_number": "TK-2024-03-9912741",
        "amount_net": 39.50,
        "amount_vat": 7.51,
        "amount_gross": 47.01,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 0.98,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Deutsche Telekom AG · Rechnung Mobilfunk März 2024 · Netto: 39,50 EUR · USt 19%: 7,51 EUR",
    },
    # ---- AUTO-TRIAGED: OK (VST_7 - Reduced rate 7%) ----
    {
        "filename": "fachbuch_python.pdf",
        "vendor": "O'Reilly Media GmbH",
        "invoice_date": "2024-01-20",
        "invoice_number": "OR-DE-2024-00293",
        "amount_net": 41.12,
        "amount_vat": 2.88,
        "amount_gross": 44.00,
        "vat_rate": 7.0,
        "category": "VST_7",
        "country": "DE",
        "status": "ok",
        "confidence": 0.91,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "O'Reilly Media GmbH · Python Cookbook 4th Ed · ISBN 978-3-96459-123-4 · USt 7%: 2,88 EUR",
    },
    {
        "filename": "springer_fachzeitschrift.pdf",
        "vendor": "Springer Fachmedien Wiesbaden GmbH",
        "invoice_date": "2024-02-10",
        "invoice_number": "SPR-2024-028471",
        "amount_net": 56.07,
        "amount_vat": 3.93,
        "amount_gross": 60.00,
        "vat_rate": 7.0,
        "category": "VST_7",
        "country": "DE",
        "status": "ok",
        "confidence": 0.89,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Springer Fachmedien · Fachzeitschrift IT-Spektrum Jahresabo · USt 7%: 3,93 EUR",
    },
    {
        "filename": "thalia_buecher.pdf",
        "vendor": "Thalia Bücher GmbH",
        "invoice_date": "2024-03-12",
        "invoice_number": "TH-2024-0394712",
        "amount_net": 46.73,
        "amount_vat": 3.27,
        "amount_gross": 50.00,
        "vat_rate": 7.0,
        "category": "VST_7",
        "country": "DE",
        "status": "ok",
        "confidence": 0.88,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Thalia Bücher GmbH · 3x Fachbücher (ISBN) · Ermäßigter Steuersatz 7%: 3,27 EUR",
    },
    # ---- AUTO-TRIAGED: OK (VST_0_EU - EU Reverse Charge) ----
    {
        "filename": "atlassian_jan2024.pdf",
        "vendor": "Atlassian Network Services, Inc.",
        "invoice_date": "2024-01-22",
        "invoice_number": "AT-EUR-2024-00128374",
        "amount_net": 77.48,
        "amount_vat": 0.00,
        "amount_gross": 77.48,
        "vat_rate": 0.0,
        "category": "VST_0_EU",
        "country": "IE",
        "status": "ok",
        "confidence": 0.92,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Atlassian Network Services, Inc. · Jira Software + Confluence · IE VAT Reg: IE9700053D · Reverse charge: §13b applicable · 0% VAT",
    },
    {
        "filename": "stripe_feb2024.pdf",
        "vendor": "Stripe Payments Europe, Ltd.",
        "invoice_date": "2024-02-28",
        "invoice_number": "STR-IE-2024-0082741",
        "amount_net": 124.30,
        "amount_vat": 0.00,
        "amount_gross": 124.30,
        "vat_rate": 0.0,
        "category": "VST_0_EU",
        "country": "IE",
        "status": "ok",
        "confidence": 0.90,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Stripe Payments Europe, Ltd. · Payment processing fees · Reverse charge applies · EU B2B: 0% VAT",
    },
    # ---- AUTO-TRIAGED: OK (NICHT_ABZIEHBAR - Not deductible) ----
    {
        "filename": "berufshaftpflicht_2024.pdf",
        "vendor": "Allianz Versicherungs-AG",
        "invoice_date": "2024-01-01",
        "invoice_number": "AZ-2024-PR-00293847",
        "amount_net": 210.08,
        "amount_vat": 39.92,
        "amount_gross": 250.00,
        "vat_rate": 19.0,
        "category": "NICHT_ABZIEHBAR",
        "country": "DE",
        "status": "ok",
        "confidence": 0.94,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Allianz Versicherungs-AG · Berufshaftpflichtversicherung · Versicherungssteuer nicht abziehbar",
    },
    # ---- CORRECTED (were wrong, manually fixed) ----
    {
        "filename": "restaurant_feb.pdf",
        "vendor": "Cantina Bella Vista GmbH",
        "invoice_date": "2024-02-20",
        "invoice_number": "CBV-2024-0082",
        "amount_net": 84.03,
        "amount_vat": 15.97,
        "amount_gross": 100.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "correction_category": "NICHT_ABZIEHBAR",
        "country": "DE",
        "status": "corrected",
        "confidence": 0.52,
        "ai_flag": True,
        "ai_reason": "Possible entertainment/meal expense. Bewirtungskosten are generally not VAT-deductible unless strictly business (§4 Nr. 22 EStG).",
        "correction_reason": "Kundenbewirtung - Vorsteuer nicht abziehbar gem. §15 Abs. 1a UStG",
        "correction_percentage": 0,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Cantina Bella Vista · Bewirtungsrechnung · Tisch für 4 Personen · Speisen & Getränke",
    },
    {
        "filename": "amazon_mixed_jan.pdf",
        "vendor": "Amazon EU S.à r.l.",
        "invoice_date": "2024-01-28",
        "invoice_number": "AMZ-EU-2024-7483920-1",
        "amount_net": 37.81,
        "amount_vat": 7.19,
        "amount_gross": 45.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "correction_category": "NICHT_ABZIEHBAR",
        "country": "LU",
        "status": "corrected",
        "confidence": 0.48,
        "ai_flag": True,
        "ai_reason": "Amazon order appears to contain personal items (Haushaltsware). Please verify if entirely business use.",
        "correction_reason": "Bestellung enthält private Artikel (Haushalt) - nicht abziehbar",
        "correction_percentage": 0,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Amazon EU S.à r.l. · Bestellung #302-7483920-1 · Haushaltsartikel + 1x USB-Kabel · Netto: 37,81 EUR",
    },
    {
        "filename": "freelancer_poland_mar.pdf",
        "vendor": "Jan Kowalski (Freiberufler)",
        "invoice_date": "2024-03-15",
        "invoice_number": "JK/2024/03/001",
        "amount_net": 1200.00,
        "amount_vat": 0.00,
        "amount_gross": 1200.00,
        "vat_rate": 0.0,
        "category": "VST_0_EU",
        "correction_category": "VST_0_EU",
        "country": "PL",
        "status": "corrected",
        "confidence": 0.71,
        "ai_flag": True,
        "ai_reason": "EU freelancer invoice (PL). Confirm reverse charge applies for innergemeinschaftliche Leistung. Check if vendor has valid EU VAT ID.",
        "correction_reason": "Bestätigt: innergemeinschaftliche Leistung, §13b UStG, Reverse Charge korrekt",
        "correction_percentage": 100,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Jan Kowalski · Faktura VAT · Webentwicklung März 2024 · NIP: PL1234567890 · Steuerfreie innergemeinschaftliche Leistung",
    },
    # ---- DELETED ----
    {
        "filename": "duplicate_hetzner.pdf",
        "vendor": "Hetzner Online GmbH",
        "invoice_date": "2024-01-01",
        "invoice_number": "R2401-2847391",
        "amount_net": 14.24,
        "amount_vat": 2.71,
        "amount_gross": 16.95,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "deleted",
        "confidence": 0.97,
        "ai_flag": True,
        "ai_reason": "Duplicate: identical invoice number R2401-2847391 already exists in this session.",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Hetzner Online GmbH · DUPLICATE · Rechnung R2401-2847391",
    },
    {
        "filename": "privatrechnung_jan.pdf",
        "vendor": "Sky Deutschland GmbH",
        "invoice_date": "2024-01-15",
        "invoice_number": "SKY-2024-01-29847",
        "amount_net": 12.60,
        "amount_vat": 2.40,
        "amount_gross": 15.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "deleted",
        "confidence": 0.31,
        "ai_flag": True,
        "ai_reason": "Sky Deutschland is a consumer TV subscription service. Likely private/personal expense.",
        "correction_reason": "Privates TV-Abo — kein Betriebsausgabe",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Sky Deutschland GmbH · Sky Entertainment Paket · Privatabo",
    },
    # ---- TO REVIEW (~10 invoices) ----
    {
        "filename": "github_copilot_jan.pdf",
        "vendor": "GitHub, Inc.",
        "invoice_date": "2024-01-16",
        "invoice_number": "GH-2024-01-COPILOT-298374",
        "amount_net": 18.49,
        "amount_vat": 0.00,
        "amount_gross": 18.49,
        "vat_rate": 0.0,
        "category": "VST_0_DRITTLAND",
        "country": "US",
        "status": "to_review",
        "confidence": 0.82,
        "ai_flag": True,
        "ai_reason": "GitHub, Inc. is a US entity (Microsoft subsidiary). Reverse charge under §13b UStG applies. Verify: no German VAT number on invoice.",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "GitHub, Inc. · GitHub Copilot Individual · 19.00 USD · US entity, no VAT charged · Customer: DE VAT registered",
    },
    {
        "filename": "figma_jan2024.pdf",
        "vendor": "Figma, Inc.",
        "invoice_date": "2024-01-18",
        "invoice_number": "FIG-2024-01-0039271",
        "amount_net": 14.99,
        "amount_vat": 0.00,
        "amount_gross": 14.99,
        "vat_rate": 0.0,
        "category": "VST_0_DRITTLAND",
        "country": "US",
        "status": "to_review",
        "confidence": 0.79,
        "ai_flag": True,
        "ai_reason": "Figma, Inc. billed from US. §13b reverse charge likely. Confirm this is the professional plan used for client work.",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Figma, Inc. · Figma Professional Plan · Billed from: San Francisco, CA · Customer VAT: DE...",
    },
    {
        "filename": "openai_feb2024.pdf",
        "vendor": "OpenAI, L.L.C.",
        "invoice_date": "2024-02-01",
        "invoice_number": "OAI-2024-02-INV-9283741",
        "amount_net": 42.50,
        "amount_vat": 0.00,
        "amount_gross": 42.50,
        "vat_rate": 0.0,
        "category": "VST_0_DRITTLAND",
        "country": "US",
        "status": "to_review",
        "confidence": 0.88,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "OpenAI, L.L.C. · API Usage Feb 2024 · No VAT charged (US entity) · §13b UStG reverse charge",
    },
    {
        "filename": "dropbox_feb2024.pdf",
        "vendor": "Dropbox, Inc.",
        "invoice_date": "2024-02-08",
        "invoice_number": "DBX-2024-02-00827349",
        "amount_net": 9.99,
        "amount_vat": 0.00,
        "amount_gross": 9.99,
        "vat_rate": 0.0,
        "category": "VST_0_DRITTLAND",
        "country": "US",
        "status": "to_review",
        "confidence": 0.83,
        "ai_flag": True,
        "ai_reason": "Dropbox billed from US. Confirm business use (not personal file storage).",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Dropbox, Inc. · Business Starter · Billing country: US · No EU VAT applied",
    },
    {
        "filename": "canva_pro_feb.pdf",
        "vendor": "Canva Pty Ltd.",
        "invoice_date": "2024-02-12",
        "invoice_number": "CNV-AU-2024-0039817",
        "amount_net": 12.99,
        "amount_vat": 0.00,
        "amount_gross": 12.99,
        "vat_rate": 0.0,
        "category": "VST_0_DRITTLAND",
        "country": "AU",
        "status": "to_review",
        "confidence": 0.76,
        "ai_flag": True,
        "ai_reason": "Canva is billed from Australia (non-EU, non-US). §13b UStG reverse charge applies for sonstige Leistungen from Drittland.",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Canva Pty Ltd. · Canva Pro · ABN: 71 620 928 013 · Sydney, Australia · No VAT",
    },
    {
        "filename": "laptop_purchase_feb.pdf",
        "vendor": "MediaMarkt Saturn National GmbH",
        "invoice_date": "2024-02-20",
        "invoice_number": "MM-2024-02-8273641",
        "amount_net": 1260.50,
        "amount_vat": 239.50,
        "amount_gross": 1500.00,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "to_review",
        "confidence": 0.65,
        "ai_flag": True,
        "ai_reason": "Large hardware purchase (€1,500). Verify: 100% business use? Mixed private/business laptops may require partial deduction. Also consider GWG rules (<€800 netto = direct deduction).",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "MediaMarkt · MacBook Pro 14\" M3 · Netto: 1.260,50 EUR · USt 19%: 239,50 EUR · Brutto: 1.500,00 EUR",
    },
    {
        "filename": "unknown_scan_001.pdf",
        "vendor": "Unbekannt (PDF nicht lesbar)",
        "invoice_date": "2024-02-25",
        "invoice_number": "",
        "amount_net": 0.00,
        "amount_vat": 0.00,
        "amount_gross": 0.00,
        "vat_rate": 0.0,
        "category": "VST_19",
        "country": "DE",
        "status": "to_review",
        "confidence": 0.12,
        "ai_flag": True,
        "ai_reason": "PDF could not be parsed reliably (possibly scanned image). Manual review required. Amount, vendor, and date could not be extracted.",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "[PDF extraction failed — image-based PDF or corrupted file]",
    },
    {
        "filename": "linkedin_premium_mar.pdf",
        "vendor": "LinkedIn Ireland Unlimited Company",
        "invoice_date": "2024-03-01",
        "invoice_number": "LI-IE-2024-03-00192837",
        "amount_net": 34.45,
        "amount_vat": 0.00,
        "amount_gross": 34.45,
        "vat_rate": 0.0,
        "category": "VST_0_EU",
        "country": "IE",
        "status": "to_review",
        "confidence": 0.78,
        "ai_flag": True,
        "ai_reason": "LinkedIn Premium billed from Ireland (EU). Innergemeinschaftliche Leistung likely. Confirm business use for network/recruiting vs. personal networking.",
        "source": "demo",
        "direction": "incoming",
        "raw_text": "LinkedIn Ireland Unlimited Company · LinkedIn Premium Career · VAT Reg IE: IE6388047V · Reverse charge",
    },
    {
        "filename": "zoom_mar2024.pdf",
        "vendor": "Zoom Video Communications, Inc.",
        "invoice_date": "2024-03-05",
        "invoice_number": "ZM-2024-03-INV-1928374",
        "amount_net": 13.32,
        "amount_vat": 0.00,
        "amount_gross": 13.32,
        "vat_rate": 0.0,
        "category": "VST_0_DRITTLAND",
        "country": "US",
        "status": "to_review",
        "confidence": 0.84,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Zoom Video Communications, Inc. · Pro Plan · San Jose, CA, USA · Business use confirmed",
    },
    {
        "filename": "steuerberatung_q1.pdf",
        "vendor": "Kanzlei Dr. Fischer & Partner mbB",
        "invoice_date": "2024-03-20",
        "invoice_number": "FP-2024-Q1-00293",
        "amount_net": 450.00,
        "amount_vat": 85.50,
        "amount_gross": 535.50,
        "vat_rate": 19.0,
        "category": "VST_19",
        "country": "DE",
        "status": "to_review",
        "confidence": 0.88,
        "ai_flag": False,
        "source": "demo",
        "direction": "incoming",
        "raw_text": "Dr. Fischer & Partner mbB Steuerberatungsgesellschaft · Honorar Q1 Buchführung · Netto: 450,00 EUR · USt 19%: 85,50 EUR",
    },
    # ---- OUTGOING INVOICES (for ELSTER income side) ----
    {
        "filename": "ausgangsrechnung_2024_001.pdf",
        "vendor": "Webdesign Projekt — Muster GmbH Berlin",
        "invoice_date": "2024-01-31",
        "invoice_number": "2024-001",
        "amount_net": 4200.00,
        "amount_vat": 798.00,
        "amount_gross": 4998.00,
        "vat_rate": 19.0,
        "category": "UST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 1.0,
        "ai_flag": False,
        "source": "demo",
        "direction": "outgoing",
        "raw_text": "Ausgangsrechnung 2024-001 · Kunde: Muster GmbH · Webentwicklung Januar 2024",
    },
    {
        "filename": "ausgangsrechnung_2024_002.pdf",
        "vendor": "API Consulting — TechCorp GmbH Hamburg",
        "invoice_date": "2024-02-15",
        "invoice_number": "2024-002",
        "amount_net": 6800.00,
        "amount_vat": 1292.00,
        "amount_gross": 8092.00,
        "vat_rate": 19.0,
        "category": "UST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 1.0,
        "ai_flag": False,
        "source": "demo",
        "direction": "outgoing",
        "raw_text": "Ausgangsrechnung 2024-002 · Kunde: TechCorp GmbH · Backend-Entwicklung",
    },
    {
        "filename": "ausgangsrechnung_2024_003.pdf",
        "vendor": "Software Development — Nordic Tech AB",
        "invoice_date": "2024-02-28",
        "invoice_number": "2024-003",
        "amount_net": 3500.00,
        "amount_vat": 0.00,
        "amount_gross": 3500.00,
        "vat_rate": 0.0,
        "category": "UST_0_EU_B2B",
        "country": "SE",
        "status": "ok",
        "confidence": 1.0,
        "ai_flag": False,
        "source": "demo",
        "direction": "outgoing",
        "raw_text": "Ausgangsrechnung 2024-003 · Kunde: Nordic Tech AB · SE VAT: SE559012345601 · Steuerfreie innergemeinschaftliche Lieferung",
    },
    {
        "filename": "ausgangsrechnung_2024_004.pdf",
        "vendor": "SaaS Consulting — US Startup LLC",
        "invoice_date": "2024-03-10",
        "invoice_number": "2024-004",
        "amount_net": 2800.00,
        "amount_vat": 0.00,
        "amount_gross": 2800.00,
        "vat_rate": 0.0,
        "category": "UST_0_EXPORT",
        "country": "US",
        "status": "ok",
        "confidence": 1.0,
        "ai_flag": False,
        "source": "demo",
        "direction": "outgoing",
        "raw_text": "Ausgangsrechnung 2024-004 · US Startup LLC · Export, steuerfrei § 4 Nr. 1a UStG",
    },
    {
        "filename": "ausgangsrechnung_2024_005.pdf",
        "vendor": "Onlineshop Relaunch — Retail AG München",
        "invoice_date": "2024-03-28",
        "invoice_number": "2024-005",
        "amount_net": 7500.00,
        "amount_vat": 1425.00,
        "amount_gross": 8925.00,
        "vat_rate": 19.0,
        "category": "UST_19",
        "country": "DE",
        "status": "ok",
        "confidence": 1.0,
        "ai_flag": False,
        "source": "demo",
        "direction": "outgoing",
        "raw_text": "Ausgangsrechnung 2024-005 · Kunde: Retail AG · E-Commerce Relaunch Projekt",
    },
]


def load_demo_data(quarter: int = 1, year: int = 2024):
    """Clear existing data and insert all demo invoices."""
    clear_all_invoices()
    loaded = []
    for inv in DEMO_INVOICES:
        inv_copy = dict(inv)
        inv_copy["quarter"] = quarter
        inv_copy["year"] = year
        inserted = insert_invoice(inv_copy)
        loaded.append(inserted)
    return loaded


def get_demo_stats() -> dict:
    incoming = get_invoices(direction="incoming")
    outgoing = get_invoices(direction="outgoing")

    statuses = {}
    for inv in incoming:
        s = inv["status"]
        statuses[s] = statuses.get(s, 0) + 1

    return {
        "total_incoming": len(incoming),
        "total_outgoing": len(outgoing),
        "by_status": statuses,
        "to_review": statuses.get("to_review", 0),
        "ok": statuses.get("ok", 0),
        "corrected": statuses.get("corrected", 0),
        "deleted": statuses.get("deleted", 0),
    }
